### ISSUE TITLE
[Bug][Server] Cannot generate binding form benchmark-action/github-action-benchmark@v1

### ISSUE THREAD

**Issue by krzema12** [typesafegithub/github-workflows-kt#1562]
```
23:29:40.606 [eventLoopGroupProxy-4-3] ERROR ktor.application -- Unhandled: GET - /benchmark-action/github-action-benchmark/v1/github-action-benchmark-v1.pom
java.lang.IllegalArgumentException: index 1 for '%"' not in range (received 0 arguments)
	at com.squareup.kotlinpoet.CodeBlock$Builder.add(CodeBlock.kt:313)
	at com.squareup.kotlinpoet.Documentable$Builder.addKdoc(Documentable.kt:27)
	at com.squareup.kotlinpoet.ParameterSpec$Builder.addKdoc(ParameterSpec.kt:150)
	at io.github.typesafegithub.workflows.actionbindinggenerator.generation.GenerationKt.buildCommonConstructorParameters(Generation.kt:395)
	at io.github.typesafegithub.workflows.actionbindinggenerator.generation.GenerationKt.primaryConstructor(Generation.kt:364)
	at io.github.typesafegithub.workflows.actionbindinggenerator.generation.GenerationKt.generateActionClass(Generation.kt:169)
	at io.github.typesafegithub.workflows.actionbindinggenerator.generation.GenerationKt.generateActionBindingSourceCode(Generation.kt:128)
	at io.github.typesafegithub.workflows.actionbindinggenerator.generation.GenerationKt.generateBinding(Generation.kt:87)
	at io.github.typesafegithub.workflows.actionbindinggenerator.generation.GenerationKt.generateBinding$default(Generation.kt:69)
	at io.github.typesafegithub.workflows.mavenbinding.JarBuildingKt.generateBinding(JarBuilding.kt:62)
	at io.github.typesafegithub.workflows.mavenbinding.JarBuildingKt.buildJars(JarBuilding.kt:35)
	at io.github.typesafegithub.workflows.mavenbinding.VersionArtifactsBuildingKt.buildVersionArtifacts(VersionArtifactsBuilding.kt:17)
	at io.github.typesafegithub.workflows.jitbindingserver.MainKt$artifact$1$bindingArtifacts$1.invokeSuspend(Main.kt:106)
	at io.github.typesafegithub.workflows.jitbindingserver.MainKt$artifact$1$bindingArtifacts$1.invoke(Main.kt)
	at io.github.typesafegithub.workflows.jitbindingserver.MainKt$artifact$1$bindingArtifacts$1.invoke(Main.kt)
```

**Comment by krzema12** [comment]
Probably this line is problematic: https://github.com/benchmark-action/github-action-benchmark/blob/fe4e90e7735310d03ca4b1d8f0eb1d425c55be00/action.yml#L61

**Comment by krzema12** [comment]
See https://github.com/square/kotlinpoet/issues/887

We need to add some more sanitization here: https://github.com/typesafegithub/github-workflows-kt/blob/eddf44456bbd8fe943a722d04c8a6d9816941e08/action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt#L444-L452
