### ISSUE TITLE
[Action wrapper(s) request] superfly/flyctl-actions/setup-flyctl@master

### ISSUE THREAD

**Issue by madhead** [typesafegithub/github-workflows-kt#595]
### Are you sure the action(s) you want aren't already supported?

No, it's not supported yet

### What action(s) do you need?

- superfly/flyctl-actions/setup-flyctl@v1
  - https://github.com/superfly/flyctl-actions/tree/master/setup-flyctl

Read more about them: https://fly.io/docs/app-guides/continuous-deployment-with-github-actions

Note that this action is not using the default and recommended project layout. I.e. they have `action.yml` in a subdirectory.

Thus, I was not able to quickly make the generator (`./gradlew :wrapper-generator:run`) work generate anything for it. I got either

```
Generating superfly/flyctl-actions@setup-flyctl
Exception in thread "main" java.lang.IllegalArgumentException: Only major versions are supported, and 'setup-flyctl' was given!
        at it.krzeminski.githubactions.wrappergenerator.generation.GenerationKt.generateWrapper(Generation.kt:48)
        at it.krzeminski.githubactions.wrappergenerator.generation.GenerationKt.generateWrapper$default(Generation.kt:44)
        at it.krzeminski.githubactions.wrappergenerator.GenerationEntryPointKt.generateWrappers(GenerationEntryPoint.kt:39)
        at it.krzeminski.githubactions.wrappergenerator.GenerationEntryPointKt.main(GenerationEntryPoint.kt:28)
        at it.krzeminski.githubactions.wrappergenerator.GenerationEntryPointKt.main(GenerationEntryPoint.kt)
```

or

```
Generating flyctl-actions/setup-flyctl@v1
  ... from https://raw.githubusercontent.com/flyctl-actions/setup-flyctl/dbf1fa04f4d2e52c33185153d06cdb5443aa189d/action.yml
  ... from https://raw.githubusercontent.com/flyctl-actions/setup-flyctl/dbf1fa04f4d2e52c33185153d06cdb5443aa189d/action.yaml
Exception in thread "main" java.lang.IllegalStateException: flyctl-actions/setup-flyctl@v1
†Can't fetch any of those URLs:
- https://raw.githubusercontent.com/flyctl-actions/setup-flyctl/dbf1fa04f4d2e52c33185153d06cdb5443aa189d/action.yml
- https://raw.githubusercontent.com/flyctl-actions/setup-flyctl/dbf1fa04f4d2e52c33185153d06cdb5443aa189d/action.yaml
Check release page https://github.com/flyctl-actions/setup-flyctl/releases
        at it.krzeminski.githubactions.wrappergenerator.metadata.MetadataReadingKt.fetchMetadata(MetadataReading.kt:64)
        at it.krzeminski.githubactions.wrappergenerator.metadata.MetadataReadingKt.fetchMetadata$default(MetadataReading.kt:48)
        at it.krzeminski.githubactions.wrappergenerator.generation.GenerationKt$generateWrapper$1.invoke(Generation.kt:46)
        at it.krzeminski.githubactions.wrappergenerator.generation.GenerationKt$generateWrapper$1.invoke(Generation.kt:46)
        at it.krzeminski.githubactions.wrappergenerator.generation.GenerationKt.generateWrapper(Generation.kt:52)
        at it.krzeminski.githubactions.wrappergenerator.generation.GenerationKt.generateWrapper$default(Generation.kt:44)
        at it.krzeminski.githubactions.wrappergenerator.GenerationEntryPointKt.generateWrappers(GenerationEntryPoint.kt:39)
        at it.krzeminski.githubactions.wrappergenerator.GenerationEntryPointKt.main(GenerationEntryPoint.kt:28)
        at it.krzeminski.githubactions.wrappergenerator.GenerationEntryPointKt.main(GenerationEntryPoint.kt)
```

When trying to run it with three / two levels accordingly.

**Comment by krzema12** [comment]
Hi @madhead! Yeah, this action will require an adjustment in the wrapper generator module. I'll take a closer look at it once I'm back from vacation.

**Comment by krzema12** [comment]
I also see a problem with versioning of this particular action - it doesn't provide a major version tag, and since some time it's mandatory to reduce maintenance burden in this DSL library. See https://krzema12.github.io/github-workflows-kt/user-guide/using-actions/#requirements-for-adding-a-new-action for more details. So even if we implement support for actions that exist in some subdirectory, this action will need to have the major version tag published.

**Comment by madhead** [comment]
Sure, wesołych Świąt i szczęśliwego Nowego Roku!

**Comment by krzema12** [comment]
@madhead could you talk to the action author to add the missing major version tag?

**Comment by krzema12** [comment]
Depends on https://github.com/krzema12/github-workflows-kt/issues/646

**Comment by krzema12** [comment]
Support for nested actions (actions in subdirectories) has been added, so now it's only a matter of the major version tag to add support for this action.

**Comment by krzema12** [comment]
@madhead since this ticket is blocked (not actionable now), I'm going to close it for now. Once the action provides the major version tag/branch, please reopen.

**Comment by krzema12** [comment]
@madhead the action owner added the major version tag! :tada:
